### ISSUE TITLE
Add Analytics Tracking

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly.github.io#2]
Add analytics tracking on following items

- [ ] Chrome and Firefox installation buttons
- [ ] Donate button
- [ ] Navigation menu actions
- [ ] Social Marketing buttons
